# Generated by Django 5.2.17 on 2026-09-09 11:28

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("registration_number", models.CharField(max_length=32, unique=True)),
                (
                    "vin",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-HJ-NPR-Z0-9]{17}$", "Use a 17-character VIN without I, O or Q."
                            )
                        ],
                    ),
                ),
                ("make", models.CharField(max_length=80)),
                ("model_name", models.CharField(max_length=80)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("MAINTENANCE", "Maintenance"),
                            ("RETIRED", "Retired"),
                        ],
                        default="ACTIVE",
                        max_length=11,
                    ),
                ),
                (
                    "connectivity_status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                        ],
                        default="UNKNOWN",
                        max_length=7,
                    ),
                ),
                (
                    "movement_status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Unknown"),
                            ("MOVING", "Moving"),
                            ("PARKED", "Parked"),
                        ],
                        default="UNKNOWN",
                        max_length=7,
                    ),
                ),
                (
                    "last_latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "last_longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                ("last_telemetry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="customers.customerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9_-]+$", "Use letters, digits, underscores or hyphens."
                            )
                        ],
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="device",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1900)), name="vehicle_year_minimum"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("vin", django.db.models.functions.text.Upper("vin"))),
                name="vehicle_vin_uppercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "registration_number",
                        django.db.models.functions.text.Upper("registration_number"),
                    )
                ),
                name="vehicle_registration_uppercase",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "MAINTENANCE", "RETIRED"])),
                name="vehicle_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("connectivity_status__in", ["UNKNOWN", "ONLINE", "OFFLINE"])),
                name="vehicle_valid_connectivity",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("movement_status__in", ["UNKNOWN", "MOVING", "PARKED"])),
                name="vehicle_valid_movement",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("last_latitude__isnull", True), ("last_longitude__isnull", True)),
                    models.Q(
                        ("last_latitude__gte", -90),
                        ("last_latitude__isnull", False),
                        ("last_latitude__lte", 90),
                        ("last_longitude__gte", -180),
                        ("last_longitude__isnull", False),
                        ("last_longitude__lte", 180),
                    ),
                    _connector="OR",
                ),
                name="vehicle_valid_coordinates",
            ),
        ),
    ]
