# Generated by Django 5.2.17 on 2026-09-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="geofence_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="geofence_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="geofence_radius_m",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("geofence_latitude__isnull", True),
                        ("geofence_longitude__isnull", True),
                        ("geofence_radius_m__isnull", True),
                    ),
                    models.Q(
                        ("geofence_latitude__isnull", False),
                        ("geofence_longitude__isnull", False),
                        ("geofence_radius_m__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="vehicle_geofence_all_or_nothing",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("geofence_radius_m__isnull", True),
                    models.Q(("geofence_radius_m__gte", 50), ("geofence_radius_m__lte", 100000)),
                    _connector="OR",
                ),
                name="vehicle_geofence_radius_range",
            ),
        ),
    ]
