# Generated by Django 5.2.17 on 2026-09-09 11:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rules_version", models.CharField(max_length=32)),
                ("rules_snapshot", models.JSONField()),
                ("input_snapshot", models.JSONField()),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "risk_band",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                        max_length=6,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Demo approved"),
                            ("REVIEW", "Review required"),
                            ("REJECTED", "Demo rejected"),
                        ],
                        max_length=8,
                    ),
                ),
                ("factors", models.JSONField()),
                ("ratios", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_assessments",
                        to="customers.customerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["customer", "-created_at"], name="credit_customer_created_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 300), ("score__lte", 850)),
                        name="credit_score_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("risk_band__in", ["LOW", "MEDIUM", "HIGH"])),
                        name="credit_valid_risk_band",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("decision__in", ["APPROVED", "REVIEW", "REJECTED"])),
                        name="credit_valid_decision",
                    ),
                ],
            },
        ),
    ]
