# Generated by Django 5.2.17 on 2026-09-09 10:50

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_user_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "phone",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+[1-9][0-9]{7,14}$", "Use + and 8–15 digits."
                            )
                        ],
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("EMPLOYED", "Employed"),
                            ("SELF_EMPLOYED", "Self-employed"),
                            ("UNEMPLOYED", "Unemployed"),
                            ("STUDENT", "Student"),
                            ("RETIRED", "Retired"),
                        ],
                        max_length=16,
                    ),
                ),
                ("employment_duration_months", models.PositiveIntegerField(default=0)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("GHS", "Ghanaian cedi"),
                            ("NGN", "Nigerian naira"),
                            ("USD", "US dollar"),
                        ],
                        default="GHS",
                        max_length=3,
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "existing_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "monthly_debt_repayment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("monthly_income__gte", 0)),
                        name="customer_income_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("existing_debt__gte", 0)),
                        name="customer_debt_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("monthly_debt_repayment__gte", 0)),
                        name="customer_repayment_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency__in", ["GHS", "NGN", "USD"])),
                        name="customer_valid_currency",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "employment_status__in",
                                ["EMPLOYED", "SELF_EMPLOYED", "UNEMPLOYED", "STUDENT", "RETIRED"],
                            )
                        ),
                        name="customer_valid_employment",
                    ),
                ],
            },
        ),
    ]
