# Generated by Django 5.2.17 on 2026-09-09 13:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("PAYSTACK", "Paystack (test mode)"),
                            ("MOCK_MOMO", "Simulated mobile money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("signature", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField()),
                ("delivery_reference", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSED", "Processed"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="RECEIVED",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-received_at", "id"],
                "indexes": [
                    models.Index(fields=["provider", "-received_at"], name="webhook_provider_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["RECEIVED", "PROCESSED", "IGNORED"])),
                        name="webhookevent_valid_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("PAYSTACK", "Paystack (test mode)"),
                            ("MOCK_MOMO", "Simulated mobile money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=64, unique=True)),
                ("currency", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("raw_event", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "indexes": [
                    models.Index(fields=["loan", "-created_at"], name="payment_loan_created_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="payment_positive_amount"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["PENDING", "SUCCESS", "FAILED", "CANCELLED"])
                        ),
                        name="payment_valid_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("provider__in", ["PAYSTACK", "MOCK_MOMO"])),
                        name="payment_valid_provider",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency__in", ["GHS", "NGN", "USD"])),
                        name="payment_valid_currency",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("provider_transaction_id__isnull", False), ("status", "SUCCESS")
                            ),
                            ("status__in", ["PENDING", "FAILED", "CANCELLED"]),
                            _connector="OR",
                        ),
                        name="payment_success_has_provider_transaction",
                    ),
                ],
            },
        ),
    ]
