# Generated by Django 5.2.17 on 2026-09-09 13:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("device_id", models.CharField(max_length=64)),
                ("recorded_at", models.DateTimeField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "speed_kph",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("heading_degrees", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("battery_percent", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ignition", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_records",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-recorded_at"], name="telemetry_vehicle_recorded_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("device_id", "recorded_at"), name="telemetry_unique_device_time"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__gte", -90),
                            ("latitude__lte", 90),
                            ("longitude__gte", -180),
                            ("longitude__lte", 180),
                        ),
                        name="telemetry_valid_coordinates",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("speed_kph__gte", 0)),
                        name="telemetry_nonnegative_speed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("heading_degrees__gte", 0), ("heading_degrees__lte", 360)
                        ),
                        name="telemetry_valid_heading",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("battery_percent__gte", 0), ("battery_percent__lte", 100)
                        ),
                        name="telemetry_valid_battery",
                    ),
                ],
            },
        ),
    ]
