# Generated by Django 5.2.17 on 2026-09-09 14:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("GEOFENCE_EXIT", "Vehicle left its geofence"),
                            ("SPEEDING", "Speed above threshold"),
                            ("LOW_BATTERY", "Device battery low"),
                            ("OFFLINE", "Vehicle offline"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                        max_length=8,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "-created_at"], name="alert_vehicle_created_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("vehicle", "type"),
                        name="alert_one_open_per_vehicle_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("type__in", ["GEOFENCE_EXIT", "SPEEDING", "LOW_BATTERY", "OFFLINE"])
                        ),
                        name="alert_valid_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("severity__in", ["LOW", "MEDIUM", "HIGH"])),
                        name="alert_valid_severity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("resolved_at__isnull", True),
                            ("resolved_by__isnull", False),
                            _connector="OR",
                        ),
                        name="alert_manual_resolve_requires_actor",
                    ),
                ],
            },
        ),
    ]
