# Generated by Django 5.2.17 on 2026-09-09 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry", "0002_alert"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="alert",
            name="alert_manual_resolve_requires_actor",
        ),
    ]
