# Generated by Django 5.2.17 on 2026-09-09 12:05

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("credit", "0001_initial"),
        ("customers", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("principal_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("annual_interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("duration_months", models.PositiveSmallIntegerField()),
                ("first_repayment_date", models.DateField()),
                ("total_interest", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_repayable", models.DecimalField(decimal_places=2, max_digits=14)),
                ("monthly_repayment", models.DecimalField(decimal_places=2, max_digits=14)),
                ("final_repayment", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("DEFAULTED", "Defaulted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=9,
                    ),
                ),
                ("policy_version", models.CharField(max_length=32)),
                ("origination_snapshot", models.JSONField()),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="credit.creditassessment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="RepaymentInstallment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("due_date", models.DateField()),
                ("principal_due", models.DecimalField(decimal_places=2, max_digits=14)),
                ("interest_due", models.DecimalField(decimal_places=2, max_digits=14)),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installments",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("PENDING", "ACTIVE", "DEFAULTED"))),
                fields=("vehicle",),
                name="loan_one_open_per_vehicle",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(("principal_amount__gt", 0)), name="loan_positive_principal"
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("annual_interest_rate__gte", 0), ("annual_interest_rate__lte", 100)
                ),
                name="loan_valid_rate",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_months__gte", 1), ("duration_months__lte", 120)),
                name="loan_valid_duration",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_interest__gte", 0),
                    (
                        "total_repayable",
                        django.db.models.expressions.CombinedExpression(
                            models.F("principal_amount"), "+", models.F("total_interest")
                        ),
                    ),
                ),
                name="loan_total_matches_components",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(("final_repayment__gt", 0), ("monthly_repayment__gt", 0)),
                name="loan_positive_repayments",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outstanding_balance__gte", 0),
                    ("outstanding_balance__lte", models.F("total_repayable")),
                ),
                name="loan_balance_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__in", ["GHS", "NGN", "USD"])),
                name="loan_valid_currency",
            ),
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("outstanding_balance", 0),
                        ("status__in", ["PENDING", "CANCELLED", "COMPLETED"]),
                    ),
                    models.Q(
                        ("outstanding_balance__gt", 0), ("status__in", ["ACTIVE", "DEFAULTED"])
                    ),
                    _connector="OR",
                ),
                name="loan_status_balance_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymentinstallment",
            constraint=models.UniqueConstraint(
                fields=("loan", "number"), name="installment_unique_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymentinstallment",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gte", 1)), name="installment_positive_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="repaymentinstallment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "amount_due",
                        django.db.models.expressions.CombinedExpression(
                            models.F("principal_due"), "+", models.F("interest_due")
                        ),
                    ),
                    ("interest_due__gte", 0),
                    ("principal_due__gt", 0),
                ),
                name="installment_valid_amounts",
            ),
        ),
    ]
