from decimal import Decimal

POLICY_VERSION = "demo-flat-v1"
MAX_ASSESSMENT_AGE_DAYS = 30
MAX_COMBINED_DEBT_TO_INCOME = Decimal("0.60")
MAX_FIRST_REPAYMENT_DAYS = 90
MAX_DURATION_MONTHS = 120
MAX_PRINCIPAL = Decimal("100000000.00")
MAX_ANNUAL_RATE = Decimal("100.00")
OPEN_STATUSES = ("PENDING", "ACTIVE", "DEFAULTED")
